---
galaxy_info:
  author: OpenShift Health Check Team
  description: Role for collecting data from OpenShift clusters
  company: Red Hat
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
        - 22.04
  galaxy_tags:
    - openshift
    - kubernetes
    - monitoring
    - assessment

dependencies: []
