---
- name: Collect deployments information
  block:
    - name: Get deployments detailed information
      command: "{{ cli_command }} get deployments --all-namespaces -o json"
      register: deployments_json_result
      environment: "{{ cluster_env | default({'KUBECONFIG': openshift_kubeconfig}) }}"

    - name: Get replicasets
      command: "{{ cli_command }} get replicasets --all-namespaces -o json"
      register: replicasets_json_result
      environment: "{{ cluster_env | default({'KUBECONFIG': openshift_kubeconfig}) }}"
      failed_when: false

    - name: Get daemonsets
      command: "{{ cli_command }} get daemonsets --all-namespaces -o json"
      register: daemonsets_json_result
      environment: "{{ cluster_env | default({'KUBECONFIG': openshift_kubeconfig}) }}"
      failed_when: false

    - name: Get statefulsets
      command: "{{ cli_command }} get statefulsets --all-namespaces -o json"
      register: statefulsets_json_result
      environment: "{{ cluster_env | default({'KUBECONFIG': openshift_kubeconfig}) }}"
      failed_when: false

    - name: Get jobs
      command: "{{ cli_command }} get jobs --all-namespaces -o json"
      register: jobs_json_result
      environment: "{{ cluster_env | default({'KUBECONFIG': openshift_kubeconfig}) }}"
      failed_when: false

    - name: Get cronjobs
      command: "{{ cli_command }} get cronjobs --all-namespaces -o json"
      register: cronjobs_json_result
      environment: "{{ cluster_env | default({'KUBECONFIG': openshift_kubeconfig}) }}"
      failed_when: false

    - name: Save deployments data to file
      copy:
        content: |
          {
            "deployments_json": {{ deployments_json_result.stdout }},
            "replicasets_json": {{ replicasets_json_result.stdout | default('{}') }},
            "daemonsets_json": {{ daemonsets_json_result.stdout | default('{}') }},
            "statefulsets_json": {{ statefulsets_json_result.stdout | default('{}') }},
            "jobs_json": {{ jobs_json_result.stdout | default('{}') }},
            "cronjobs_json": {{ cronjobs_json_result.stdout | default('{}') }},
            "collection_metadata": {{ collection_metadata | to_nice_json }}
          }
        dest: "{{ data_output_dir }}/deployments.json"
        mode: '0644'

    - name: Set fact for deployments collection status
      set_fact:
        collection_status:
          deployments: true

    - name: Display deployments collection status
      debug:
        msg: "Deployments information collected successfully"

  rescue:
    - name: Handle deployments collection failure
      debug:
        msg: "Failed to collect deployments information: {{ ansible_failed_result.msg }}"
      
    - name: Set fact for deployments collection status
      set_fact:
        collection_status:
          deployments: false
