---
# Configuração de Exemplo - OpenShift Health Check SEM FinOps
# Este arquivo demonstra como configurar a ferramenta excluindo funcionalidades de FinOps
# Copie este arquivo para group_vars/all.yml e customize conforme necessário

# ===========================================
# CONFIGURAÇÕES DE CONEXÃO OPENSHIFT
# ===========================================
openshift_cluster_url: "https://api.cluster.example.com:6443"
openshift_token: "sha256~seu-token-aqui"
openshift_kubeconfig: "~/.kube/config"
openshift_context: ""

# ===========================================
# CONFIGURAÇÕES DE COLETA DE DADOS
# ===========================================
collect_cluster_info: true
collect_nodes: true
collect_namespaces: true
collect_pods: true
collect_services: true
collect_deployments: true
collect_rbac: true
collect_security_configs: true
collect_operators: true
collect_metrics: true
collect_events: true

# Filtros de coleta (opcional)
namespace_filter: ""
label_selector: ""
field_selector: ""

# ===========================================
# CONFIGURAÇÕES DE ANÁLISE DE ARQUITETURA
# ===========================================
analyze_cluster_overview: true
analyze_node_architecture: true
analyze_network_architecture: true
analyze_storage_architecture: true
analyze_operator_health: true
analyze_resource_distribution: true

# Thresholds de arquitetura
min_master_nodes: 3
min_worker_nodes: 2
max_node_cpu_usage: 80
max_node_memory_usage: 80
max_pod_density_per_node: 100

# Configurações de rede
check_network_policies: true
check_ingress_controllers: true
check_load_balancers: true

# Configurações de storage
check_persistent_volumes: true
check_storage_classes: true
check_volume_snapshots: true

# ===========================================
# CONFIGURAÇÕES DE ANÁLISE DE SEGURANÇA
# ===========================================
analyze_rbac: true
analyze_network_security: true
analyze_pod_security: true
analyze_secrets_management: true
analyze_compliance: true

# Thresholds de segurança
max_privileged_containers: 0
max_root_containers: 0
max_host_network_pods: 0
max_host_pid_pods: 0
max_host_ipc_pods: 0

# Configurações de RBAC
check_excessive_permissions: true
check_privileged_service_accounts: true
check_cluster_admin_usage: true

# Configurações de segurança de rede
check_network_policies: true
check_ingress_security: true
check_dns_security: true

# Frameworks de conformidade
check_cis_benchmarks: true
check_nist_guidelines: true
check_pod_security_standards: true

# ===========================================
# CONFIGURAÇÕES DE ANÁLISE DE BOAS PRÁTICAS
# ===========================================
# Configurações de melhores práticas
best_practices_settings:
  min_quota_coverage: 80
  min_limit_coverage: 80
  min_health_check_coverage: 80
  min_backup_coverage: 60
  min_monitoring_coverage: 70
  enforce_naming_conventions: true
  naming_pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  max_name_length: 63
  required_labels:
    - "app"
    - "version"
    - "component"
  require_readiness_probe: true
  require_liveness_probe: true

# ===========================================
# CONFIGURAÇÕES DE OTIMIZAÇÃO DE RECURSOS (SEM FINOPS)
# ===========================================
# Análise de recursos (sem análise de custos)
analyze_cpu_utilization: true
analyze_memory_utilization: true
analyze_storage_utilization: true
analyze_node_optimization: true
analyze_service_optimization: true

# ⚠️ IMPORTANTE: DESABILITAR análise de custos (FinOps)
analyze_cost_optimization: false
enable_cost_analysis: false

# Thresholds de otimização (sem custos)
cpu_utilization_threshold: 70
memory_utilization_threshold: 70
storage_utilization_threshold: 80
node_utilization_threshold: 60

# Recomendações de otimização (sem custos)
recommend_node_consolidation: true
recommend_service_optimization: true
recommend_storage_cleanup: true

# ===========================================
# CONFIGURAÇÕES DE SAÍDA E RELATÓRIOS
# ===========================================
output_dir: "{{ playbook_dir }}/../reports"
timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
compress_reports: false

# Configurações de geração de relatórios
generate_html_report: true
generate_pdf_report: false
generate_json_report: true
generate_markdown_report: true

# ===========================================
# CONFIGURAÇÕES DE TIMEOUT E LIMITES
# ===========================================
command_timeout: 300
connection_timeout: 30

# Limites de recursos para coleta de dados
max_pods_per_namespace: 1000
max_events_per_namespace: 1000
max_metrics_points: 10000

# ===========================================
# CONFIGURAÇÕES DE LOGGING
# ===========================================
log_level: "INFO"
log_format: "json"

# ===========================================
# CONFIGURAÇÕES DE VERIFICAÇÕES CUSTOMIZADAS
# ===========================================
custom_checks:
  - name: "Verificar labels específicos"
    type: "pod"
    condition: "item.metadata.labels.security == 'high'"
    severity: "warning"
    
  - name: "Verificar annotations específicas"
    type: "namespace"
    condition: "item.metadata.annotations.owner == 'security-team'"
    severity: "info"

# ===========================================
# CONFIGURAÇÕES DE NOTIFICAÇÃO (OPCIONAL)
# ===========================================
notifications:
  enabled: false
  webhook_url: ""
  slack_channel: ""
  email_recipients: []

# ===========================================
# CONFIGURAÇÕES DE INTEGRAÇÃO (OPCIONAL)
# ===========================================
integrations:
  prometheus:
    enabled: false
    url: ""
    token: ""
    
  grafana:
    enabled: false
    url: ""
    token: ""
    
  elasticsearch:
    enabled: false
    url: ""
    index: "openshift-health-check"

# ===========================================
# CONFIGURAÇÕES DE CONFORMIDADE
# ===========================================
compliance_settings:
  check_cis_benchmarks: true
  check_nist_guidelines: true
  check_pod_security_standards: true
  check_network_policies: true
  check_ingress_security: true
  check_dns_security: true

# ===========================================
# CONFIGURAÇÕES DE LOGGING AVANÇADO
# ===========================================
logging_settings:
  level: "INFO"
  format: "json"
  file: "{{ playbook_dir }}/logs/health_check.log"
  max_size: "10MB"
  backup_count: 5
